### ISSUE TITLE
git clone stop while `resolving deltas`

### ISSUE THREAD

**Issue by astronaut1712** [ish-app/ish#943]
git version: both 2.24.3-r0 and 2.28.0-r1
alpine: 3.11 (default included in iSH)

**Comment by astronaut1712** [comment]
![image](https://user-images.githubusercontent.com/2898284/95879721-de462700-0da0-11eb-86ff-2ce2c87f0ce3.jpeg)

**Comment by tbodt** [comment]
Could you try installing iSH build 75 to see if it used to work there?

**Comment by saagarjha** [comment]
Also, what device do you have?

**Comment by astronaut1712** [comment]
I run on iPad Pro 2020 11inch.

**Comment by saagarjha** [comment]
We suspect this is an internal concurrency issue that we have only observed on devices with the A12Z chipset; running git single-threaded will likely work around your issue for now. We’re looking into getting a better understanding of this bug, so if someone sees it on other hardware please do let us know!

**Comment by astronaut1712** [comment]
> Could you try installing iSH build 75 to see if it used to work there?

I tried installing build 75, but it got the same error.

**Comment by saagarjha** [comment]
Was there a reason you closed this issue?

**Comment by filfat** [comment]
@saagarjha this occurs for me on both iPhone XS Max and iPad Pro (2018)

**Comment by filfat** [comment]
@saagarjha you asked about an example repo, https://github.com/JSPrismarine/JSPrismarine hangs at resolving deltas

**Comment by tommycusick** [comment]
Just came across this issue and filed feedback within the app, but for posterity, `git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew` also causes the git command to hang indefinitely at “Resolving deltas.”

**Comment by mjgardner** [comment]
Also having this problem. git 2.26.2, iSH 1.1.1 (Build 91), trying to clone git://github.com/mjgardner/LWPx-UserAgent-Cached.git

**Comment by mjgardner** [comment]
> We suspect this is an internal concurrency issue that we have only observed on devices with the A12Z chipset; running git single-threaded will likely work around your issue for now. We’re looking into getting a better understanding of this bug, so if someone sees it on other hardware please do let us know!

How do you run git single-threaded?

**Comment by tommycusick** [comment]
> We suspect this is an internal concurrency issue that we have only observed on devices with the A12Z chipset; running git single-threaded will likely work around your issue for now. We’re looking into getting a better understanding of this bug, so if someone sees it on other hardware please do let us know!

@saagarjha FYI, see comments from @mjgardner and myself from the past few days which show cases where it’s happening on chips older than A12Z.  At least in my case, I’m able to reproduce it reliably, so please let me know what other information would be useful for debugging.

**Comment by atommclain** [comment]
> > We suspect this is an internal concurrency issue that we have only observed on devices with the A12Z chipset; running git single-threaded will likely work around your issue for now. We’re looking into getting a better understanding of this bug, so if someone sees it on other hardware please do let us know!
> 
> How do you run git single-threaded?

I was able to get around the issue with this command: git config --global pack.threads "1"

**Comment by 8thHalfHour** [comment]
Same problem here. It was intermittent, and now it’s on every one of my devices: iPhone 7 Plus, iPad Air 2, and iPad Pro 12.9” (2018). Until yesterday, I could usually `^C` out of the situation and `reboot` or `halt`, and it would then work (as long as I had removed any trace that some files had been actually transferred (i.e., del a directory, remove files, whatever). But now it’s constant. For me, it’s the oh-my-zsh repo, something I’ve installed on all of my devices in iSH a thousand times with no issues. Now, I get some variation of the following:

![C3ED4104-0E9C-4979-AD79-3DACEDF7DCE8](https://user-images.githubusercontent.com/44852729/110248063-1ef73600-7f24-11eb-9e2c-1f090bbe8f02.jpeg)

I’m also getting an `IO ERROR` when `OpenSSL` is upgraded. I know we are tracking this elsewhere, and I will add to that issue, but since I am unsure if they are related, I thought I’d note that little nugget here, too.

**Comment by wachabaha** [comment]
**_[
](https://user-images.githubusercontent.com/221021/107689800-29444e00-6c5e-11eb-804f-d4b76cb72e82.png)_**

**Comment by rechka** [comment]
adding --depth <some small integer> helps

**Comment by therocketforever** [comment]
Hello, just adding to the pile.

same issue, doesn't matter what repo, or how large / long history is. Fails to fetch ruby, fails to fetch git, fails on some private repos I tried. 

I concur with the suspicion it's related to threading. Ruby 3.0.1 required a patch for threading to build ( downloaded a tar to get around git hanging )

Declaring `git config --global pack.threads "1"` & re running clone/fetch/pull seems to be working on all repositories I try now

iOS 14.4.2
iPhone X
iSH 1.2 ( build 149 )

**Comment by sofianhw** [comment]
> git config --global pack.threads "1"

its help

**Comment by kmgolden** [comment]
Just reporting that this issue occurred for me on an M1 iPadPro, and the single threading resolved the issue.

**Comment by shaysugg** [comment]
Same here on my iPad Air 2020
Also add the single thread config hasn't fixed the problem

**Comment by Michale-wang** [comment]
This issue occurred for me on an iPhone 11(iOS 15.2), and the single threading resolved my issue.

**Comment by sflomenb** [comment]
This was happening to me on my 2018 11” iPad Pro, and the single thread change resolved it for me. Thanks!

**Comment by jkelol111** [comment]
Unfortunately the single threaded mode fix didn’t work for me on the M1 iPad Pro.

**Comment by 0n1cOn3** [comment]
Issue persists on iPhone 12, current BetaFlight Version. It's broken since Oktober 2021. 1 Thread fix doesnt work eighter.

**Comment by HackUnit** [comment]
Reporting that the single thread fix worked here.

iOS 15.2.1
iPad Pro 1st Generation
iSH 1.2.3 (Build 298)

**Comment by saagarjha** [comment]
Hi! We understand that this is an important issue and it’s something we’re looking into. While we appreciate discussion about workarounds while we work to fix this, we really don’t need any more confirmation that running git single-threaded does not exhibit the issue. If you have any new information to share we’d be happy to hear it but for now we’d ask for people to please refrain from posting "this workaround fixed the issue for me" comments because they only clutter up the conversation without adding any new information. I've collapsed the existing ones for now.

**Comment by carl0zen** [comment]
> Hello, just adding to the pile.
> 
> same issue, doesn't matter what repo, or how large / long history is. Fails to fetch ruby, fails to fetch git, fails on some private repos I tried.
> 
> I concur with the suspicion it's related to threading. Ruby 3.0.1 required a patch for threading to build ( downloaded a tar to get around git hanging )
> 
> Declaring `git config --global pack.threads "1"` & re running clone/fetch/pull seems to be working on all repositories I try now
> 
> iOS 14.4.2 iPhone X iSH 1.2 ( build 149 )

I can confirm it is fixing the issue with deltas, I could clone a repo without issues., running Alpine 3.11

**Comment by Imjek** [comment]
Resolving deltas forever !

**Comment by laddge** [comment]
Using an older version of git and single thread solved it for me.

  Model: iPad Air 4th gen
  OS: iPad OS 15.3.1
  iSH: v1.2.3

Try following command.

```
apk del git
wget https://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86/git-2.24.4-r0.apk
apk add ./git-2.24.4-r0.apk
git config —global pack.threads “1”
```

**Comment by aotsukiqx** [comment]
> Using an older version of git and single thread solved it for me.
> 
> Model: iPad Air 4th gen OS: iPad OS 15.3.1 iSH: v1.2.3
> 
> Try following command.
> 
> ```
> apk del git
> wget https://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86/git-2.24.4-r0.apk
> apk add ./git-2.24.4-r0.apk
> git config —global pack.threads “1”
> ```

This works!

**Comment by till213** [comment]
Hello,

I just stumbled over the exact same issue here, git clone seems to be stuck at „Resolving deltas“ (CTRL + C an restarting git clone came as far as „5%“ - but then stuck again).

As a matter of fact I have just deleted and re-installed the iSH app (for other reasons), so it is considered a „fresh install“ (plus, all the required development packages, git, openssh etc. all added with „apk add“).

* iPad Air, 3rd generation, 64 GB
* iOS 15.3.1 (latest at the time of this writing)
* Latest iSH at the time of this writing (re-installed from App Store just today)
* Repository: https://github.com/till213/SkyDolly.git

git --version
git version 2.32.0
uname -a
Linux Olis-Airbag 4.20.69-ish iSH 1.2.3 (298) Dec 17 2021 06:08:24 i686 Linux

Setting git config —global pack.threads “1” as described above worked (as a workaround).

**Comment by saagarjha** [comment]
I'm going to close this as it should be resolved by https://github.com/ish-app/ish/commit/947e640b819bd136deac73edc7ff2379f3813805 and the fix will ship in the next version of iSH.

**Comment by sam-rad** [comment]
I had the same issue and I did:

```
apk upgrade git

git --version  
# git version 2.32.0
```

and it was sorted out on my iPhone.

**Comment by TurtleMeds** [comment]
> I had the same issue and I did:
> 
> ```
> apk upgrade git
>```
can confirm this worked for me as well

**Comment by peterbehr** [comment]
> ```
> 
> apk del git
> 
> wget https://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86/git-2.24.4-r0.apk
> 
> apk add ./git-2.24.4-r0.apk
> 
> git config —global pack.threads “1”
> 
> ```

Workaround works! But this comment and ones quoting it should also be minimized, since the double dash and straight double quotes have been converted to en-dash and curly double quotes. Maybe by iOS? Should be:

```
apk del git
wget https://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86/git-2.24.4-r0.apk
apk add ./git-2.24.4-r0.apk
git config --global pack.threads "1" 
```

**Comment by Edgeburn** [comment]
> Using an older version of git and single thread solved it for me.
> 
> 
> 
>   Model: iPad Air 4th gen
> 
>   OS: iPad OS 15.3.1
> 
>   iSH: v1.2.3
> 
> 
> 
> Try following command.
> 
> 
> 
> ```
> 
> apk del git
> 
> wget https://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86/git-2.24.4-r0.apk
> 
> apk add ./git-2.24.4-r0.apk
> 
> git config —global pack.threads “1”
> 
> ```

Doesn't work on iPad Pro M1. It got further resolving deltas (30% -> 75%) but still hangs.

**Comment by LW-Andres** [comment]
> > Using an older version of git and single thread solved it for me.
> > Model: iPad Air 4th gen
> > OS: iPad OS 15.3.1
> > iSH: v1.2.3
> > Try following command.
> > ```
> > 
> > apk del git
> > 
> > wget https://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86/git-2.24.4-r0.apk
> > 
> > apk add ./git-2.24.4-r0.apk
> > 
> > git config —global pack.threads “1”
> > ```
> 
> Doesn't work on iPad Pro M1. It got further resolving deltas (30% -> 75%) but still hangs.

It worked on iPhone 12 pro

**Comment by cloudhzc** [comment]
> o
When I do 'wget https://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86/git-2.24.4-r0.apk',it stop at 5%

**Comment by andreyFreeman** [comment]
Same issue for me

**Comment by king-piyush** [comment]
I solved this problem by this command
git config --global pack.threads "1"

**Comment by andreyFreeman** [comment]
> I solved this problem by this command
> git config --global pack.threads "1"

I tried as well, still hangs but on one of steps before resolving deltas

**Comment by dotHTM** [comment]
Still an issue running iPad Pro M2 (2022), iOS 16.1, iSH version 1.2.3 build 298.

Config command mentioned above still a good workaround.

**Comment by professor123456788** [comment]
> Could you try installing iSH build 75 to see if it used to work there?

I have iPhone 7plus and iam using ish shell uname linux and i also face this problem resolving deltas stop in 0

**Comment by professor123456788** [comment]
I have iPhone 7plus and iam using ish shell uname linux and i also face this problem resolving deltas stop in 0 In setoolkit

**Comment by srgustafson8** [comment]
I just had this issue with a fresh ish install on an M2 iPad Pro. Git version is `2.32.4`, and the single thread workaround did fix it, but this issue should be reopened as it's not resolved.

**Comment by xero** [comment]
i also just had this issue on a fresh install on a 3rd gen ipad m1 pro 11”

**Comment by squishypixel** [comment]
Issue persists on iPad Pro 12.9. Single thread workaround results in sticking during `remote: counting objects`.

**Comment by ArcticDev78** [comment]
Unable to run "git add ." on old iPad Air running iOS 12.5.7

**Comment by boydkelly** [comment]
Installed a fedora 38 container/minimal image and getting this.   Tried the global.pack.threads =1 options but no success.

**Comment by KDelu** [comment]
> adding --depth <some small integer> helps i noticed this problem only on repos with loooooong history of commits, who needs them all?

Changing the --depth worked for me 
Tried the global.pack.threads =1 options but no success.
On version 2.39.3 of git
Macbook Pro 16" 2019

**Comment by Rod-at-DOH** [comment]
I am having the same issue:

![image](https://github.com/ish-app/ish/assets/127354181/197af291-ed95-4d4b-8a38-2649f8822e64)

It has been stuck there for 3 hours, with no change at all. I'm running this on an HP desktop with an i9 processor.

**Comment by Rod-at-DOH** [comment]
I found an issue about this  on GitHub. I've added my voice to the thread. But honestly, this is a hung impediment to doing anything else.

I'm going to let Paul Leo, the contractor who wrote IBIS, know. Not that he can do anything about it. 

But really, this is a major productivity killer.
